// Tree-shaking optimized icon imports - only imports icons actually used in the application
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Bookmark,
  BookmarkPlus,
  Bot,
  Calendar,
  Check,
  CheckCircle,
  ChefHat,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Coffee,
  Copy,
  Crown,
  Database,
  DollarSign,
  Download,
  Droplets,
  ExternalLink,
  Eye,
  Facebook,
  FileText,
  Flame,
  Heart,
  History,
  Home,
  Instagram,
  Lock,
  LogIn,
  Mail,
  Menu,
  MessageCircle,
  Moon,
  Plus,
  Printer,
  RefreshCw,
  Refrigerator,
  Scale,
  Search,
  Send,
  Settings,
  Share2,
  ShoppingCart,
  Signal,
  Smartphone,
  Smile,
  Sparkles,
  Star,
  Sun,
  Timer,
  Trash2,
  Twitter,
  User,
  UserPlus,
  Users,
  Utensils,
  UtensilsCrossed,
  Wine,
  X,
  Zap,
} from "lucide-react";

// Only export icons that are actually used in the application
export const optimizedIconMap = {
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  bookmark: Bookmark,
  bookmarkPlus: BookmarkPlus,
  bot: Bot,
  calendar: Calendar,
  check: Check,
  checkCircle: CheckCircle,
  chefHat: ChefHat,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock,
  coffee: Coffee,
  copy: Copy,
  crown: Crown,
  database: Database,
  dollarSign: DollarSign,
  download: Download,
  droplets: Droplets,
  externalLink: ExternalLink,
  eye: Eye,
  facebook: Facebook,
  fileText: FileText,
  flame: Flame,
  heart: Heart,
  history: History,
  home: Home,
  instagram: Instagram,
  lock: Lock,
  login: LogIn,
  mail: Mail,
  menu: Menu,
  messageCircle: MessageCircle,
  moon: Moon,
  plus: Plus,
  printer: Printer,
  refresh: RefreshCw,
  refrigerator: Refrigerator,
  scale: Scale,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  shoppingCart: ShoppingCart,
  signal: Signal,
  smartphone: Smartphone,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  timer: Timer,
  trash2: Trash2,
  twitter: Twitter,
  user: User,
  userPlus: UserPlus,
  users: Users,
  utensils: Utensils,
  utensilsCrossed: UtensilsCrossed,
  wine: Wine,
  x: X,
  zap: Zap,
} as const;

export type OptimizedIconName = keyof typeof optimizedIconMap;